### ISSUE TITLE
MatchError 

### ISSUE THREAD

**Issue by novakov-alexey** [twilio/sbt-guardrail#10]
`sbt compile` throws scala.MatchError for swagger file https://raw.githubusercontent.com/aeternity/aeternity/master/config/swagger.yaml

scala version: 2.12.8
sbt plugin: addSbtPlugin("com.twilio" % "sbt-guardrail" % "0.37.1-M1")
sbt: 1.2.8

Stack trace:
```
[error] scala.MatchError: io.swagger.models.ComposedModel@a95c8fbf (of class io.swagger.models.ComposedModel)
[error] 	at com.twilio.guardrail.SwaggerUtil$.$anonfun$modelMetaType$1(SwaggerUtil.scala:114)
[error] 	at cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:87)
[error] 	at cats.data.Kleisli.$anonfun$flatMap$2(Kleisli.scala:31)
[error] 	at cats.data.WriterT.$anonfun$flatMap$1(WriterT.scala:44)
[error] 	at cats.package$$anon$1.flatMap(package.scala:40)
[error] 	at cats.data.WriterT.flatMap(WriterT.scala:43)
[error] 	at cats.data.WriterTFlatMap1.flatMap(WriterT.scala:324)
[error] 	at cats.data.WriterTFlatMap1.flatMap$(WriterT.scala:323)
[error] 	at cats.data.WriterTInstances3$$anon$4.flatMap(WriterT.scala:185)
[error] 	at cats.data.WriterTInstances3$$anon$4.flatMap(WriterT.scala:185)
[error] 	at cats.data.Kleisli.$anonfun$flatMap$1(Kleisli.scala:31)
[error] 	at cats.data.WriterT.$anonfun$flatMap$1(WriterT.scala:44)
[error] 	at cats.package$$anon$1.flatMap(package.scala:40)
[error] 	at cats.data.WriterT.flatMap(WriterT.scala:43)
[error] 	at cats.data.WriterTFlatMap1.flatMap(WriterT.scala:324)
[error] 	at cats.data.WriterTFlatMap1.flatMap$(WriterT.scala:323)
[error] 	at cats.data.WriterTInstances3$$anon$4.flatMap(WriterT.scala:185)
[error] 	at cats.data.WriterTInstances3$$anon$4.flatMap(WriterT.scala:185)
[error] 	at cats.data.Kleisli$.$anonfun$shift$1(Kleisli.scala:106)
[error] 	at cats.data.Kleisli.$anonfun$map$1(Kleisli.scala:19)
[error] 	at cats.data.Kleisli.$anonfun$flatMap$1(Kleisli.scala:31)
[error] 	at cats.data.WriterT.$anonfun$flatMap$1(WriterT.scala:44)
[error] 	at cats.package$$anon$1.flatMap(package.scala:40)
[error] 	at cats.data.WriterT.flatMap(WriterT.scala:43)
[error] 	at cats.data.WriterTFlatMap1.flatMap(WriterT.scala:324)
[error] 	at cats.data.WriterTFlatMap1.flatMap$(WriterT.scala:323)
[error] 	at cats.data.WriterTInstances3$$anon$4.flatMap(WriterT.scala:185)
[error] 	at cats.data.WriterTInstances3$$anon$4.flatMap(WriterT.scala:185)
[error] 	at cats.data.Kleisli$.$anonfun$shift$1(Kleisli.scala:106)
[error] 	at cats.data.Kleisli.$anonfun$map$1(Kleisli.scala:19)
[error] 	at cats.data.Kleisli.$anonfun$map$1(Kleisli.scala:19)
[error] 	at cats.data.Kleisli.$anonfun$flatMap$2(Kleisli.scala:31)
[error] 	at cats.data.WriterT.$anonfun$flatMap$1(WriterT.scala
```

**Comment by blast-hardcheese** [comment]
@novakov-alexey Thanks for the report! Could you try again using version 0.43.0? 0.44.0 has been authored to support OpenAPI 3.x, but due to an unexpected classloader bug, the sbt plugin is currently not working for all configurations.

**Comment by novakov-alexey** [comment]
@blast-hardcheese Just checked `0.43.0`. It generates client successfully. Thanks.
